app:
  scheduler:
    fixed-delay: 2000
    batch_size: 10

  client:
    yandex-speller:
      connect-timeout: 5000
      read-timeout: 30000

spring:
  jackson:
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/error_free_text
    username: postgres
    password: 12345